/**
 * Catalog Module - Frontend Utilities
 * 
 * Re-exports all catalog API functions.
 * All functions use v2 API endpoints.
 */

export {
  // Products - Read
  fetchProducts,
  fetchProduct,
  fetchProductStats,
  // Products - Create
  createProduct,
  // Products - Update
  updateProduct,
  updateProductStatus,
  // Products - Delete
  deleteProduct,
  deleteProducts,
  // Products - Images
  fetchProductImages,
  uploadProductImage,
  deleteProductImage,
  setPrimaryImage,
  // Variations (legacy; v2 TBD)
  fetchVariationTypes,
  createVariationType,
  fetchVariationValues,
  createVariationValue,
  deleteVariationType,
  createProductVariationRecord,
  uploadProductImagesBulk,
  // Products - Inventory
  fetchProductInventory,
  updateProductInventory,
  fetchInventory,
  updateInventory,
  fetchInventoryHistory,
  fetchAllInventoryHistory,
  // Categories - Read
  fetchCategories,
  fetchAllCategories,
  fetchCategory,
  // Categories - CRUD (admin)
  createCategory,
  updateCategory,
  deleteCategory,
  // Categories - Content (admin)
  fetchCategoryContent,
  updateCategoryContent,
  // Categories - SEO (admin)
  fetchCategorySeo,
  updateCategorySeo,
  // Categories - Products (admin)
  fetchCategoryProducts,
  addCategoryProduct,
  removeCategoryProduct,
  // Categories - Search (admin)
  searchCategoryProducts,
  searchCategoryVendors,
  // Categories - Change Log (admin)
  fetchCategoryChangeLog,
  // Categories - Upload (admin)
  uploadCategoryImages,
  // Collections
  fetchCollections,
  fetchCollection,
  createCollection,
  updateCollection,
  reorderCollections,
  deleteCollection,
  fetchCollectionProducts,
  addProductToCollection,
  removeProductFromCollection,
  // Import/Export
  exportProducts,
  downloadTemplate,
  getImportStatus,
  // Public (no auth)
  fetchPublicProducts,
  fetchPublicProduct,
  fetchPublicCollection,
  // Walmart connector (v2 catalog addon)
  fetchWalmartCategories,
  fetchWalmartProducts,
  fetchWalmartProduct,
  saveWalmartProduct,
  removeWalmartProduct,
  fetchWalmartAdminProducts,
  activateWalmartProduct,
  pauseWalmartProduct,
  updateWalmartAdminProduct,
  // Wayfair connector (v2 catalog addon)
  fetchWayfairCategories,
  fetchWayfairProducts,
  fetchWayfairProduct,
  saveWayfairProduct,
  updateWayfairProduct,
  removeWayfairProduct,
  fetchWayfairAllocations,
  testWayfairConnection,
  fetchWayfairAdminProducts,
  activateWayfairProduct,
  pauseWayfairProduct,
  rejectWayfairProduct,
  updateWayfairAdminProduct,
  // TikTok connector (v2 catalog addon)
  fetchTikTokShops,
  fetchTikTokProducts,
  saveTikTokProduct,
  tiktokOAuthAuthorize,
  fetchTikTokCorporateProducts,
  fetchTikTokCorporateProduct,
  saveTikTokCorporateProduct,
  removeTikTokCorporateProduct,
  fetchTikTokAllocations,
  saveTikTokAllocation,
  bulkTikTokAllocations,
  fetchTikTokLogs,
  fetchTikTokAdminProducts,
  activateTikTokProduct,
  pauseTikTokProduct,
  updateTikTokAdminProduct,
  // Shopify connector (v2 catalog addon)
  fetchShopifyShops,
  disconnectShopifyShop,
  shopifyOAuthAuthorize,
  fetchShopifyProducts,
  saveShopifyProduct,
  fetchShopifyAllocations,
  saveShopifyAllocation,
  bulkShopifyAllocations,
  fetchShopifyLogs,
  testShopifyConnection,
  fetchShopifyAdminProducts,
  activateShopifyProduct,
  pauseShopifyProduct,
  updateShopifyAdminProduct,
  // Etsy connector (v2 catalog addon)
  etsyOAuthAuthorize,
  fetchEtsyShops,
  fetchEtsyProducts,
  fetchEtsyProduct,
  saveEtsyProduct,
  updateEtsyInventory,
  fetchEtsySyncLogs,
  // Amazon connector (v2 catalog addon)
  amazonOAuthAuthorize,
  fetchAmazonShops,
  disconnectAmazonShop,
  fetchAmazonProducts,
  saveAmazonProduct,
  fetchAmazonAllocations,
  saveAmazonAllocation,
  fetchAmazonLogs,
  testAmazonConnection,
  fetchAmazonAdminProducts,
  activateAmazonProduct,
  pauseAmazonProduct,
  updateAmazonAdminProduct,
  fetchAmazonCorporateProducts,
  fetchAmazonCorporateProduct,
  saveAmazonCorporateProduct,
  removeAmazonCorporateProduct,
  // Faire connector (v2 catalog addon)
  faireOAuthAuthorize,
  fetchFaireShops,
  disconnectFaireShop,
  fetchFaireProducts,
  saveFaireProduct,
  fetchFaireAllocations,
  saveFaireAllocation,
  fetchFaireLogs,
  testFaireConnection,
  fetchFaireAdminProducts,
  activateFaireProduct,
  pauseFaireProduct,
  updateFaireAdminProduct,
  fetchFaireCorporateProducts,
  fetchFaireCorporateProduct,
  saveFaireCorporateProduct,
  removeFaireCorporateProduct,
  // Meta connector (v2 catalog addon)
  metaOAuthAuthorize,
  fetchMetaShops,
  disconnectMetaShop,
  fetchMetaProducts,
  saveMetaProduct,
  fetchMetaAllocations,
  saveMetaAllocation,
  fetchMetaLogs,
  testMetaConnection,
  fetchMetaAdminProducts,
  activateMetaProduct,
  pauseMetaProduct,
  updateMetaAdminProduct,
  fetchMetaCorporateProducts,
  fetchMetaCorporateProduct,
  saveMetaCorporateProduct,
  removeMetaCorporateProduct,
  // eBay connector (v2 catalog addon)
  fetchEbayShops,
  disconnectEbayShop,
  ebayOAuthAuthorize,
  fetchEbayProducts,
  saveEbayProduct,
  fetchEbayAllocations,
  saveEbayAllocation,
  fetchEbayLogs,
  testEbayConnection,
  fetchEbayAdminProducts,
  activateEbayProduct,
  pauseEbayProduct,
  updateEbayAdminProduct,
  fetchEbayCorporateProducts,
  fetchEbayCorporateProduct,
  saveEbayCorporateProduct,
  removeEbayCorporateProduct,
  // Curation - Marketplace Product Sorting (admin)
  fetchCurationStats,
  fetchCurationProducts,
  categorizeProduct,
  bulkCategorizeProducts,
  fetchCurationLog,
} from './api';
