CREATE INDEX `idx_artist_profiles_business` ON `artist_profiles`\n(\n  `business_name`\n);
CREATE UNIQUE INDEX `cart_id` ON `cart_applied_coupons`\n(\n  `cart_id`,\n  `coupon_id`\n);
CREATE INDEX `fk_cart_applied_coupons_coupon_id` ON `cart_applied_coupons`\n(\n  `coupon_id`\n);
CREATE INDEX `idx_cart_items_cart_id` ON `cart_items`\n(\n  `cart_id`\n);
CREATE INDEX `idx_cart_items_product_id` ON `cart_items`\n(\n  `product_id`\n);
CREATE INDEX `idx_cart_items_saved` ON `cart_items`\n(\n  `is_saved_for_later`\n);
CREATE INDEX `idx_cart_items_vendor_id` ON `cart_items`\n(\n  `vendor_id`\n);
CREATE INDEX `idx_carts_expires_at` ON `carts`\n(\n  `expires_at`\n);
CREATE INDEX `idx_carts_guest_token` ON `carts`\n(\n  `guest_token`\n);
CREATE INDEX `idx_carts_status` ON `carts`\n(\n  `status`\n);
CREATE INDEX `idx_carts_user_id` ON `carts`\n(\n  `user_id`\n);
CREATE INDEX `fk_categories_parent_id` ON `categories`\n(\n  `parent_id`\n);
CREATE UNIQUE INDEX `uk_categories_name` ON `categories`\n(\n  `name`\n);
CREATE UNIQUE INDEX `code` ON `coupons`\n(\n  `code`\n);
CREATE INDEX `idx_coupons_code` ON `coupons`\n(\n  `code`\n);
CREATE INDEX `idx_coupons_valid_until` ON `coupons`\n(\n  `valid_until`\n);
CREATE INDEX `idx_coupons_vendor_id` ON `coupons`\n(\n  `vendor_id`\n);
CREATE INDEX `idx_coupons_vendor_specific` ON `coupons`\n(\n  `is_vendor_specific`\n);
CREATE INDEX `email_verification_tokens_ibfk_1` ON `email_verification_tokens`\n(\n  `user_id`\n);
CREATE UNIQUE INDEX `token` ON `email_verification_tokens`\n(\n  `token`\n);
CREATE INDEX `idx_file_type` ON `media_library`\n(\n  `file_type`\n);
CREATE INDEX `idx_status` ON `media_library`\n(\n  `status`\n);
CREATE INDEX `idx_user_id` ON `media_library`\n(\n  `user_id`\n);
CREATE INDEX `password_reset_tokens_ibfk_1` ON `password_reset_tokens`\n(\n  `user_id`\n);
CREATE UNIQUE INDEX `token` ON `password_reset_tokens`\n(\n  `token`\n);
CREATE INDEX `permission_id` ON `permissions_log`\n(\n  `permission_id`\n);
CREATE INDEX `permissions_log_ibfk_2` ON `permissions_log`\n(\n  `user_id_changed`\n);
CREATE INDEX `permissions_log_ibfk_3` ON `permissions_log`\n(\n  `changed_by`\n);
CREATE INDEX `fk_pc_category_id` ON `product_categories`\n(\n  `category_id`\n);
CREATE INDEX `fk_pi_product_id` ON `product_images`\n(\n  `product_id`\n);
CREATE UNIQUE INDEX `uk_ps_product_package` ON `product_shipping`\n(\n  `product_id`,\n  `package_number`\n);
CREATE INDEX `fk_products_category_id` ON `products`\n(\n  `category_id`\n);
CREATE INDEX `fk_products_created_by` ON `products`\n(\n  `created_by`\n);
CREATE INDEX `fk_products_parent_id` ON `products`\n(\n  `parent_id`\n);
CREATE INDEX `fk_products_updated_by` ON `products`\n(\n  `updated_by`\n);
CREATE UNIQUE INDEX `uk_products_sku` ON `products`\n(\n  `sku`\n);
CREATE UNIQUE INDEX `vendor_sku_unique` ON `products`\n(\n  `vendor_id`,\n  `sku`\n);
CREATE INDEX `idx_promoter_profiles_business` ON `promoter_profiles`\n(\n  `business_name`\n);
CREATE INDEX `fk_sales_product_id` ON `sales`\n(\n  `product_id`\n);
CREATE UNIQUE INDEX `token` ON `saved_registrations`\n(\n  `token`\n);
CREATE INDEX `idx_user_profiles_name` ON `user_profiles`\n(\n  `first_name`,\n  `last_name`\n);
CREATE INDEX `idx_google_uid` ON `users`\n(\n  `google_uid`\n);
CREATE UNIQUE INDEX `username` ON `users`\n(\n  `username`\n);
CREATE INDEX `variant_kinds_ibfk_1` ON `variant_kinds`\n(\n  `user_id`\n);
CREATE INDEX `idx_vendor_shipping_default` ON `vendor_shipping_methods`\n(\n  `is_default`\n);
CREATE INDEX `idx_vendor_shipping_vendor_id` ON `vendor_shipping_methods`\n(\n  `vendor_id`\n);
CREATE INDEX `product_id` ON `vendor_sku_log`\n(\n  `product_id`\n);
CREATE UNIQUE INDEX `vendor_sku_unique` ON `vendor_sku_log`\n(\n  `vendor_id`,\n  `sku`\n);
