-- Migration 035: Add 'social' to terms_versions subscription_type enum
-- and insert initial Social Central terms version

-- 1. Add 'social' to the subscription_type ENUM
ALTER TABLE terms_versions
  MODIFY COLUMN subscription_type ENUM('general','verification','verified','shipping_labels','marketplace','website','websites','sites','wholesale','addons','crm','social') DEFAULT 'general';

-- 2. Also add 'social' to user_terms_acceptance subscription_type ENUM
ALTER TABLE user_terms_acceptance
  MODIFY COLUMN subscription_type ENUM('general','verification','verified','shipping_labels','marketplace','website','websites','sites','wholesale','addons','crm','social') DEFAULT 'general';

-- 3. Insert the initial terms for Social Central
INSERT INTO terms_versions (version, title, subscription_type, content, is_current, created_at)
VALUES (
  '1.0',
  'Social Central Terms of Service',
  'social',
  'By subscribing to Social Central, you agree to the following terms:\n\n1. **Service Description**: Social Central provides AI-powered social media marketing tools, including content generation, scheduling, analytics, and platform management.\n\n2. **AI Content**: Content generated by our AI (Leo and Claude) is intended as suggestions. You are responsible for reviewing and approving all content before publication.\n\n3. **Platform Connections**: When you connect social media accounts, we use OAuth to manage posting on your behalf. You may disconnect at any time.\n\n4. **Media Usage**: Media uploaded to your library is stored securely and used only for your marketing campaigns. We do not share your media with third parties.\n\n5. **Billing**: Paid tiers are billed monthly. You may upgrade or downgrade at any time. Cancellations take effect at the end of the billing period.\n\n6. **Data Privacy**: Your brand data and campaign analytics are used solely to improve your content. We never sell your data.\n\n7. **Acceptable Use**: You agree not to use Social Central to generate spam, misleading content, or content that violates platform policies.\n\n8. **Limitation of Liability**: We are not liable for actions taken by social media platforms on your accounts, including rate limits, suspensions, or content removal.',
  1,
  NOW()
);
