-- Migration 046: Corporate products tables for Amazon, eBay, Faire (hybrid pattern)
-- Follows tiktok_corporate_products schema with marketplace-specific columns

CREATE TABLE IF NOT EXISTS amazon_corporate_products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  amazon_asin VARCHAR(20) DEFAULT NULL,
  amazon_sku VARCHAR(100) DEFAULT NULL,
  corporate_title VARCHAR(500) DEFAULT NULL,
  corporate_description TEXT DEFAULT NULL,
  corporate_short_description VARCHAR(1000) DEFAULT NULL,
  corporate_key_features JSON DEFAULT NULL,
  corporate_main_image_url VARCHAR(500) DEFAULT NULL,
  corporate_additional_images JSON DEFAULT NULL,
  corporate_category VARCHAR(255) DEFAULT NULL,
  corporate_brand VARCHAR(255) DEFAULT NULL,
  corporate_condition VARCHAR(50) DEFAULT 'new_new',
  corporate_price DECIMAL(10,2) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  listing_status ENUM('pending','listed','paused','removing','removed','rejected') DEFAULT 'pending',
  sync_status ENUM('pending','syncing','synced','failed') DEFAULT 'pending',
  last_sync_at DATETIME DEFAULT NULL,
  last_sync_error TEXT DEFAULT NULL,
  terms_accepted_at DATETIME DEFAULT NULL,
  rejection_reason TEXT DEFAULT NULL,
  removed_at DATETIME DEFAULT NULL,
  cooldown_ends_at DATETIME DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_amazon_corp_product (product_id),
  INDEX idx_amazon_corp_user (user_id),
  INDEX idx_amazon_corp_listing (listing_status),
  INDEX idx_amazon_corp_sync (sync_status),
  INDEX idx_amazon_corp_active (is_active),
  INDEX idx_amazon_corp_cooldown (cooldown_ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ebay_corporate_products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  ebay_listing_id VARCHAR(100) DEFAULT NULL,
  corporate_title VARCHAR(500) DEFAULT NULL,
  corporate_description TEXT DEFAULT NULL,
  corporate_short_description VARCHAR(1000) DEFAULT NULL,
  corporate_key_features JSON DEFAULT NULL,
  corporate_main_image_url VARCHAR(500) DEFAULT NULL,
  corporate_additional_images JSON DEFAULT NULL,
  corporate_category_id VARCHAR(100) DEFAULT NULL,
  corporate_brand VARCHAR(255) DEFAULT NULL,
  corporate_condition VARCHAR(50) DEFAULT 'NEW',
  corporate_listing_format VARCHAR(50) DEFAULT 'FIXED_PRICE',
  corporate_price DECIMAL(10,2) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  listing_status ENUM('pending','listed','paused','removing','removed','rejected') DEFAULT 'pending',
  sync_status ENUM('pending','syncing','synced','failed') DEFAULT 'pending',
  last_sync_at DATETIME DEFAULT NULL,
  last_sync_error TEXT DEFAULT NULL,
  terms_accepted_at DATETIME DEFAULT NULL,
  rejection_reason TEXT DEFAULT NULL,
  removed_at DATETIME DEFAULT NULL,
  cooldown_ends_at DATETIME DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ebay_corp_product (product_id),
  INDEX idx_ebay_corp_user (user_id),
  INDEX idx_ebay_corp_listing (listing_status),
  INDEX idx_ebay_corp_sync (sync_status),
  INDEX idx_ebay_corp_active (is_active),
  INDEX idx_ebay_corp_cooldown (cooldown_ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faire_corporate_products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  faire_product_id VARCHAR(100) DEFAULT NULL,
  corporate_title VARCHAR(500) DEFAULT NULL,
  corporate_description TEXT DEFAULT NULL,
  corporate_short_description VARCHAR(1000) DEFAULT NULL,
  corporate_key_features JSON DEFAULT NULL,
  corporate_main_image_url VARCHAR(500) DEFAULT NULL,
  corporate_additional_images JSON DEFAULT NULL,
  corporate_category VARCHAR(255) DEFAULT NULL,
  corporate_brand VARCHAR(255) DEFAULT NULL,
  corporate_wholesale_price DECIMAL(10,2) DEFAULT NULL,
  corporate_retail_price DECIMAL(10,2) DEFAULT NULL,
  corporate_minimum_order_quantity INT DEFAULT 1,
  corporate_price DECIMAL(10,2) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  listing_status ENUM('pending','listed','paused','removing','removed','rejected') DEFAULT 'pending',
  sync_status ENUM('pending','syncing','synced','failed') DEFAULT 'pending',
  last_sync_at DATETIME DEFAULT NULL,
  last_sync_error TEXT DEFAULT NULL,
  terms_accepted_at DATETIME DEFAULT NULL,
  rejection_reason TEXT DEFAULT NULL,
  removed_at DATETIME DEFAULT NULL,
  cooldown_ends_at DATETIME DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_faire_corp_product (product_id),
  INDEX idx_faire_corp_user (user_id),
  INDEX idx_faire_corp_listing (listing_status),
  INDEX idx_faire_corp_sync (sync_status),
  INDEX idx_faire_corp_active (is_active),
  INDEX idx_faire_corp_cooldown (cooldown_ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
